chat/urls.py
from django.urls import path
from . import views

app_name = "chat"


urlpatterns = [
    # path('', views.chat, name="chat"),
   path('c/<str:room_name>/', views.chat_box, name='chat-user'),
]

expo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('organizer/', include('organizer.urls', namespace="organizer")),
    path('', include('user.urls', namespace="user")),
    path('message/', include('chat.urls', namespace="message")),
    path('admin/', admin.site.urls),
    path('', include('paypal.standard.ipn.urls'))
]

user/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "user"

urlpatterns = [
    path('', views.landing_page, name="landingpage"),
    path('login/', views.log_in, name="login"),
    path('logout/', views.log_out, name="logout"),
    path('register/', views.register, name="register"),
    path('activate/<uidb64>/<token>', views.activate, name="activate"),
    path('forgot_password', views.forgot_password, name="forgotpassword"),
    path('confirm_otp', views.confirm_otp, name="confirmotp"),
    path('new_password/', views.new_password, name="newpassword"),
    path('user/dashboard/', views.dashboard, name="dashboard"),

    path('user/booking/', views.booking, name="booking"),
    path('user/booking/create-booking/', views.create_booking, name="create-booking"),
    path('user/booking/create-booking/proceed-to-payment', views.proceed_to_payment, name="proceed-to-payment"),
    path('user/booking-confirmation/', views.booking_confirmed, name='booking-confirmation'),
    
    path('user/payment-history', views.payment_history, name="payment-history"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate
from .models import Booking
from organizer.models import Package

class RegistrationForm(forms.ModelForm):
    first_name = forms.CharField(
        required=True,
        label="First name:",
        max_length= 100,
        widget= forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'John'
        })
    )
    
    last_name = forms.CharField(
        required=True,
        label="Last name:",
        max_length=100,
        widget= forms.TextInput(attrs={
            'class' : 'form-control',
            'placeholder': 'Doe',
        })
    )
    
    username = forms.EmailField(
        required=True,
        label="Email:",
        max_length= 100,
        widget= forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'johndoe@gmail.com'
        })
    )

    password1 = forms.CharField(
        required=True,
        label="Password:",
        widget=forms.PasswordInput(attrs={
            'class' : 'form-control',
            'placeholder': '•••••••••',
        })
    )
    
    password2 = forms.CharField(
        required=True,
        label="Confirm Password",
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': '•••••••••',
        })
    )
    
    
    class Meta:
        model = User    
        fields = ['first_name', 'last_name', 'username', 'password1', 'password2']
        
    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")
        email = cleaned_data.get("username")

        if password1 and password2 and password1 != password2:
            self.add_error("password2", "Passwords do not match")
            
        if email and User.objects.filter(email=email).exists():
            self.add_error("username", "A user with this email already exists.")

        return cleaned_data
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["username"]
        user.password = make_password(self.cleaned_data["password1"])
        user.is_active = False
        if commit:
            user.save()
        return user
    
class LoginForm(forms.Form):
    username = forms.EmailField(
        required=True,
        label="Email:",
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'johndoe@gmail.com'
        })
    )
    password = forms.CharField(
        required=True,
        label="Password:",
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': '•••••••••'
        })
    )
    
    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('username')
        password = cleaned_data.get('password')

        if email and password:
            try:
                user = User.objects.get(email=email)  # Check if user exists
                
                if not user.is_active:
                    cleaned_data["inactive_user"] = user  # Store inactive user for the view
                    return cleaned_data  # ✅ Return without authentication

                authenticated_user = authenticate(username=user.username, password=password)
                if authenticated_user is None:
                    raise forms.ValidationError("Invalid email or password.")

                cleaned_data["user"] = authenticated_user  # Store the authenticated user

            except User.DoesNotExist:
                raise forms.ValidationError("Invalid email or password.")

        return cleaned_data
    
class BookingForm(forms.ModelForm):
    wedding_date = forms.DateField(
        required=True,
        label="Pick your wedding date:",
        widget= forms.DateInput(attrs={
            'class': 'form-control',
            'type':'date',
        }),
        
    )
    
    package = forms.ModelChoiceField(
        required=True,
        label="Select package: ",
        queryset= Package.objects.all(),
        widget=forms.Select(attrs={
            'class': 'form-select'
        })
    )
    
    class Meta:
        model = Booking
        fields = ['wedding_date', 'package']

user/views.py
from django.shortcuts import render, redirect
from django.utils.timezone import now
from django.contrib.auth import login, logout, authenticate, get_user_model
#Email activation link imports
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.http import HttpResponse
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage
# end of email
from .forms import RegistrationForm, LoginForm, BookingForm
from django.contrib import messages
from .tokens import account_activation_token
from django.urls import reverse
from django.contrib.auth.models import User
import random, json
from datetime import date
from decimal import Decimal
from organizer.models import Hero, About, Project
from django.contrib.auth.hashers import make_password
from organizer.models import Package
from .models import Booking, Payment
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string

# Paypal
from paypal.standard.forms import PayPalPaymentsForm
from django.conf import settings
import uuid

# Create your views here.

def notifyOrganizer(request):
    organizer_user = User.objects.filter(is_staff=True, is_superuser=False).first()

    mail_subject = f"You received a new booking!"
    message = render_to_string("template_organizer_message.html", {
        'client': request.user,
        'organizer': organizer_user,
    })
    email = EmailMessage(mail_subject, message, to=[organizer_user.email])
    if email.send():
        messages.success(request, 'Booking confirmed successfully!')
    
def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except:
        user = None
    
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        
        messages.success(request, 'Your email has been verified. You can now log in to your account.')
        return redirect('user:login')
    else:
        messages.error(request, 'Activation link is invalid')
    return redirect('user:login')

def activateEmail(request, user):
    mail_subject = "Activate your user account"
    message = render_to_string("template_activate_account.html", {
        'user': user,
        'domain': get_current_site(request).domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
        "protocol": 'https' if request.is_secure() else 'http'
    })
    email = EmailMessage(mail_subject, message, to=[user.email])
    if email.send():
        messages.success(request, 'Please check your email and click the activation link to activate your account.')
    else:
        messages.error(request, 'Error sending email, please check you email inputted if you typed it correctly.')
        
def sendOTPEmail(request, user_email):
    otp = str(random.randint(100000, 999999))
    request.session['otp'] = otp
    request.session['email'] = user_email
    request.session.set_expiry(300)

    mail_subject = "This is your OTP Code to reset your password"
    message = f"""
        Your One-Time Password (OTP) is {otp}
        OTP will expire in 5 minutes.
        Do not share it with anyone.
        If you did not request this, please disregard this email.
    """
    
    email = EmailMessage(mail_subject, message, to=[user_email])

    if email.send():
        messages.success(request, 'OTP has been sent successfully.')
    
def landing_page(request):
    if request.user.is_authenticated and request.user.is_staff:
        return redirect('organizer:dashboard')
    elif request.user.is_authenticated:
        return redirect('user:dashboard')
    hero = Hero.objects.first()
    about = About.objects.first()
    projects = Project.objects.order_by('-id')
    package = Package.objects.all()
    return render(request, 'user/landing_page.html', {'hero':hero, 'about':about, 'projects':projects, 'packages':package})

def log_in(request):
    if request.user.is_authenticated:
        if request.user.is_staff:
            return redirect('organizer:dashboard')
        else:
            return redirect('user:dashboard')
    
    if request.method == "POST":
        form = LoginForm(request.POST)

        if form.is_valid():
            email = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")

            try:
                user = User.objects.get(email=email)

                if not user.is_active:
                    # ✅ Send activation email if the user exists but is inactive
                    print("skibidi")
                    activateEmail(request, user)
                    messages.info(request, "Your account is not yet activated. A new activation link has been sent to your email.")
                    return redirect("user:login")  # Redirect to prevent resending on refresh

                authenticated_user = authenticate(username=user.username, password=password)
                if authenticated_user is not None:
                    login(request, authenticated_user)
                    request.session.set_expiry(1209600)

                    if authenticated_user.is_staff:
                        return redirect(reverse("organizer:dashboard"))
                    else:
                        return redirect("user:dashboard")

            except User.DoesNotExist:
                messages.error(request, "Invalid email or password.")
                return redirect("user:login")  # Redirect to prevent resending on refresh

        for error in form.errors.values():
            for message in error:
                messages.error(request, message)

    else:
        form = LoginForm()

    return render(request, "user/log_in.html", {"form": form})

def log_out(request):
    logout(request)
    return redirect('user:landingpage')

def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            activateEmail(request, user)
            return redirect('user:login')
    else:
        form = RegistrationForm()
    return render(request, 'user/register.html', {'form': form})

def forgot_password(request):
    if request.method == "POST":
        email = request.POST.get("user_email")

        if User.objects.filter(email=email).exists():
            sendOTPEmail(request, email)
            return redirect('user:confirmotp')
        else:
            messages.error(request, "Invalid email or not registered on the website.")
    
    return render (request, 'user/forgot_password.html')

def confirm_otp (request):
    if request.method == "POST":
        entered_otp = request.POST.get('otp_number')
        stored_otp = request.session.get('otp')
        user_email = request.session.get('email')
        if stored_otp and entered_otp:
            if stored_otp == entered_otp:
                del request.session['otp']
                messages.success(request, 'OTP match')
                request.session['verified_email'] = user_email
                return redirect('user:newpassword')
            else:
                messages.error(request, "Invalid OTP.")
    return render(request, 'user/confirm_otp.html')


def new_password(request):
    verified_email = request.session.get('verified_email')
    
    if not verified_email:
        messages.error(request, "Sorry! You don't have access here.")
        return redirect('user:landingpage')
    
    user_obj = User.objects.get(email=verified_email)

    if request.method == "POST":
        pass1 = request.POST.get("password1")
        pass2 = request.POST.get("password2")

        if pass1 == pass2:
            user_obj.password = make_password(pass1)
            user_obj.save()
            messages.success(request, "Password reset successfully. You can login now.")
            return redirect('user:login')
        else:
            messages.error(request, "Passwords do not match")

    return render(request,'user/new_password.html')


def dashboard(request):
    if request.user.is_authenticated:
        bookings = Booking.objects.filter(user=request.user, payment_status="pending").first()
        bookings_count = Booking.objects.filter(user=request.user).count()
        
        print(bookings)
        return render(request, 'user/dashboard.html', {'bookings': bookings, 'bookings_count':bookings_count})
    return redirect('user:landingpage')


def booking(request):
    if request.user.is_authenticated:
        
        bookings = Booking.objects.filter(user=request.user).order_by('-booking_date')
        return render(request, 'user/booking.html',{'bookings':bookings} )
        
        
    return redirect('user:landingpage')

def create_booking(request):
    if request.user.is_authenticated:
        booked_dates = [date.strftime("%Y-%m-%d") for date in Booking.objects.values_list('wedding_date', flat=True)]
        print("Booked dates: ",booked_dates)
        if request.method == "POST":
            form = BookingForm(request.POST)
            
            if form.is_valid():
                booking_data = form.cleaned_data
                package = booking_data['package']
                booking_data['username'] = request.user.username
                booking_data['wedding_date'] = booking_data['wedding_date'].strftime("%Y-%m-%d")
                booking_data['package'] = {
                    'id': package.id,
                    'package_price': float(package.package_price),
                    'package_name' : package.package_name,
                    'package_downpayment': float(package.package_downpayment)
                }

user/templates/components1/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}

      {% endblock %}
    </title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect" />
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />

    <!-- Vendor User CSS Files -->
    <link href="{% static 'assets1/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'assets1/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet" />
    <link href="{% static 'assets1/vendor/aos/aos.css' %}" rel="stylesheet" />
    <link href="{% static 'assets1/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" />
    <link href="{% static 'assets1/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet" />
    <link href="{% static 'assets1/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet" />

    <!-- Main User CSS File -->
    <link href="{% static 'assets1/css/main.css' %}" rel="stylesheet" />
  </head>
  <body class="bg-">
    {% block content %}

    {% endblock %}
    {% if messages %}
      <script>
      document.addEventListener("DOMContentLoaded", function() {
        {% for message in messages %}
            Swal.fire({
              icon: "{% if message.tags == 'success' %}success{% elif message.tags == 'error' %}error{% elif message.tags == 'warning' %}warning{% else %}info{% endif %}",
              title: "{% if message.tags == 'success' %}Success!{% elif message.tags == 'error' %}Error!{% else %}Notice{% endif %}",
                text: "{{ message|safe }}",
            });
        {% endfor %}
      });
    </script>
    {% endif %}
    <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Preloader -->
    {% comment %} <div id="preloader"></div> {% endcomment %}
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!-- Vendor JS Files -->
    <script src="{% static 'assets1/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets1/vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'assets1/vendor/aos/aos.js' %}"></script>
    <script src="{% static 'assets1/vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'assets1/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets1/vendor/swiper/swiper-bundle.min.js' %}"></script>

    <!-- Main JS File -->
    <script src="{% static 'assets1/js/main.js' %}"></script>

  </body>
</html>

user/templates/components1/footer.html
<footer id="footer" class="footer dark-background">
  <div class="container copyright text-center mt-4">
    <p>
      © <span>Copyright</span> <strong class="px-1 sitename">Vin Russel Jarcia</strong> <br>
      © <span>Copyright</span> <strong class="px-1 sitename">Expo 2025</strong> <br>
      <span>All Rights Reserved</span>
    </p>
  </div>
</footer>

user/templates/components1/navbar.html
<header id="header" class="header d-flex align-items-center fixed-top">
  <div class="container-fluid container-xl position-relative d-flex align-items-center">
    <a href="{% url 'user:landingpage' %}" class="logo d-flex align-items-center me-auto">
      <!-- Uncomment the line below if you also wish to use an image logo -->
      <!-- <img src="assets/img/logo.png" alt=""> -->
      <h1 class="sitename">E-Events</h1>
    </a>

    {% if request.path != "/login/" %}
    <nav id="navmenu" class="navmenu">
      <ul>
        <li>
          <a href="#" class="active">Home<br /></a>
        </li>
        <li>
          <a href="#about">About</a>
        </li>
        <li>
          <a href="#projects">Projects</a>
        </li>
        <li>
          <a href="#packages">Packages</a>
        </li>
        <li>
          <a href="#contactus">Contact</a>
        </li>
        <li>
          <a href="{% url 'user:login' %}" class="btn-login-nav">Log in</a>
        </li>
      </ul>
      <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
    </nav>
    {% endif %}
  </div>
</header>

user/templates/components1/sidebar.html
{% load static %}
<header id="header" class="header fixed-top d-flex align-items-center">
  <div class="d-flex align-items-center justify-content-between">
    <a href="{% url 'organizer:dashboard' %}" class="logo d-flex align-items-center">
      <img src="" alt="" />
      <span class="d-none d-lg-block">E-Events</span>
    </a>
    <i class="bi bi-list toggle-sidebar-btn"></i>
  </div>
  <!-- End Logo -->

  <nav class="header-nav ms-auto">
    <ul class="d-flex align-items-center">
      {% comment %}
      <li class="nav-item d-block d-lg-none">
        <a class="nav-link nav-icon search-bar-toggle" href="#"><i class="bi bi-search"></i></a>
      </li>
      <!-- End Search Icon -->
      {% endcomment %}

      {% comment %} <li class="nav-item dropdown">
        <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
          <i class="bi bi-bell"></i>
          <span class="badge bg-primary badge-number">4</span>
        </a><!-- End Notification Icon -->

        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
          <li class="dropdown-header">
            You have 4 new notifications
            <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
          </li>
          <li>
            <hr class="dropdown-divider" />
          </li>

          <li class="notification-item">
            <i class="bi bi-exclamation-circle text-warning"></i>
            <div>
              <h4>Lorem Ipsum</h4>
              <p>Quae dolorem earum veritatis oditseno</p>
              <p>30 min. ago</p>
            </div>
          </li>

          <li>
            <hr class="dropdown-divider" />
          </li>

          <li class="notification-item">
            <i class="bi bi-x-circle text-danger"></i>
            <div>
              <h4>Atque rerum nesciunt</h4>
              <p>Quae dolorem earum veritatis oditseno</p>
              <p>1 hr. ago</p>
            </div>
          </li>

          <li>
            <hr class="dropdown-divider" />
          </li>

          <li class="notification-item">
            <i class="bi bi-check-circle text-success"></i>
            <div>
              <h4>Sit rerum fuga</h4>
              <p>Quae dolorem earum veritatis oditseno</p>
              <p>2 hrs. ago</p>
            </div>
          </li>

          <li>
            <hr class="dropdown-divider" />
          </li>

          <li class="notification-item">
            <i class="bi bi-info-circle text-primary"></i>
            <div>
              <h4>Dicta reprehenderit</h4>
              <p>Quae dolorem earum veritatis oditseno</p>
              <p>4 hrs. ago</p>
            </div>
          </li>

          <li>
            <hr class="dropdown-divider" />
          </li>
          <li class="dropdown-footer">
            <a href="#">Show all notifications</a>
          </li>
        </ul>
        <!-- End Notification Dropdown Items -->
      </li> {% endcomment %}
      <!-- End Notification Nav -->

      {% comment %} <li class="nav-item dropdown">
        <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
          <i class="bi bi-chat-left-text"></i>
          <span class="badge bg-success badge-number">3</span>
        </a><!-- End Messages Icon -->

        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow messages">
          <li class="dropdown-header">
            You have 3 new messages
            <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
          </li>
          <li>
            <hr class="dropdown-divider" />
          </li>

          <li class="message-item">
            <a href="#">
              <img src="assets/img/messages-1.jpg" alt="" class="rounded-circle" />
              <div>
                <h4>Maria Hudson</h4>
                <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                <p>4 hrs. ago</p>
              </div>
            </a>
          </li>
          <li>
            <hr class="dropdown-divider" />
          </li>

          <li class="message-item">
            <a href="#">
              <img src="assets/img/messages-2.jpg" alt="" class="rounded-circle" />
              <div>
                <h4>Anna Nelson</h4>
                <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                <p>6 hrs. ago</p>
              </div>
            </a>
          </li>
          <li>
            <hr class="dropdown-divider" />
          </li>

          <li class="message-item">
            <a href="#">
              <img src="assets/img/messages-3.jpg" alt="" class="rounded-circle" />
              <div>
                <h4>David Muldon</h4>
                <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                <p>8 hrs. ago</p>
              </div>
            </a>
          </li>
          <li>
            <hr class="dropdown-divider" />
          </li>

          <li class="dropdown-footer">
            <a href="#">Show all messages</a>
          </li>
        </ul>
        <!-- End Messages Dropdown Items -->
      </li>
      <!-- End Messages Nav --> {% endcomment %}

      <li class="nav-item dropdown pe-3">
        <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
          <img src="{% static 'assets1/img/avatar.svg' %}" alt="Profile" class="rounded-circle" />
          <span class="d-none d-md-block dropdown-toggle ps-2">{{user.first_name|slice:":1"}}.  {{user.last_name}}</span>
        </a><!-- End Profile Iamge Icon -->

        {% if user.is_authenticated %}
        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
          <li class="dropdown-header">
            <h6>{{user.first_name}} {{ user.last_name}}</h6>
            <span>Client</span>
          </li>
          <li>
            <hr class="dropdown-divider" />
          </li>

          <li>
            <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
              <i class="bi bi-person"></i>
              <span>My Profile</span>
            </a>
          </li>
          <li>
            <hr class="dropdown-divider" />
          </li>

          <li>
            <a class="dropdown-item d-flex align-items-center" href="">
              <i class="bi bi-gear"></i>
              <span>Account Settings</span>
            </a>
          </li>
          <li>
            <hr class="dropdown-divider" />
          </li>

          {% comment %} <li>
            <a class="dropdown-item d-flex align-items-center" href="pages-faq.html">
              <i class="bi bi-question-circle"></i>
              <span>Need Help?</span>
            </a>
          </li>
          <li>
            <hr class="dropdown-divider" />
          </li> {% endcomment %}

          <li>
            <a class="dropdown-item d-flex align-items-center" href="{% url 'user:logout' %}">
              <i class="bi bi-box-arrow-right"></i>
              <span>Sign Out</span>
            </a>
          </li>
        </ul>
        <!-- End Profile Dropdown Items -->
      </li>
      <!-- End Profile Nav -->
    </ul>
    {% endif %}
  </nav>
  <!-- End Icons Navigation -->
</header>
<!-- ======= Sidebar ======= -->
<aside id="sidebar" class="sidebar">
  <ul class="sidebar-nav" id="sidebar-nav">
    <li class="nav-item">
      <a class="nav-link collapsed" href="{% url 'user:dashboard' %}">
        <i class="bi bi-grid"></i>
        <span>Dashboard</span>
      </a>
    </li>
    <!-- End Dashboard Nav -->

    <li class="nav-item">
      <a class="nav-link {% if 'booking' in request.path %} active {% else %} collapsed {% endif %}" href="{% url 'user:booking' %}">
        <i class="bi bi-book"></i>
        <span>Booking</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link collapsed" href="{% url 'user:payment-history' %}">
        <i class="bi bi-credit-card"></i>
        <span>Payments</span>
      </a>
    </li>

    {% comment %} <li class="nav-item">
      <a class="nav-link collapsed" href="">
        <i class="bi bi-star"></i>
        <span>Rate us</span>
      </a>
    </li> {% endcomment %}
    
  </ul>
  
</aside>