chat/urls.py
from django.urls import path
from . import views

app_name = "chat"


urlpatterns = [
    # path('', views.chat, name="chat"),
   path('c/<str:room_name>/', views.chat_box, name='chat-user'),
]

expo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('organizer/', include('organizer.urls', namespace="organizer")),
    path('', include('user.urls', namespace="user")),
    path('message/', include('chat.urls', namespace="message")),
    path('admin/', admin.site.urls),
    path('', include('paypal.standard.ipn.urls'))
]

organizer/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = "organizer"

urlpatterns = [
    path('dashboard/', views.index, name="dashboard"),
    path('packages/', views.packages, name="packages"),
    path('update-package/<int:id>/', views.update_package, name="update-package"),
    path('delete-package/<int:id>/', views.delete_package, name="delete-package"),
    path('bookings/', views.bookings, name="bookings"),
    path('confirm-payments/', views.confrim_payments, name="confirm-payments"),
    path('payment-history/', views.payment_history, name="payment-history"),
    path('clients/', views.manage_clients, name="clients"),
    path('suppliers/', views.manage_suppliers, name="suppliers"),
    
    path('system-settings/', views.system_settings, name="system-settings"),
    path('system-settings/update-hero', views.update_hero, name="update-hero"),
    path('system-settings/update-about', views.update_about, name="update-about"),
    
    
    path('activity-logs/', views.activity_logs, name="activity-logs"),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organizer/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.utils.html import mark_safe
from decimal import Decimal
# Create your models here.

class Package(models.Model):
    PACKAGE_TYPES = [
        ('fixed', 'Fixed'),
        ('custom', 'Custom'),
    ]

    package_name = models.CharField(max_length=150, unique=True)
    package_type = models.CharField(max_length=10, choices=PACKAGE_TYPES, default='Fixed')
    package_price = models.DecimalField(max_digits=8, decimal_places=2)
    package_downpayment = models.DecimalField(max_digits=8, decimal_places=2)
    package_inclusion = ArrayField(models.CharField(max_length=150), null=True)
    
    def save(self, *args, **kwargs):
        if self.package_type == "Fixed":
            self.package_downpayment =  Decimal(self.package_price) * Decimal('0.2')
        
        super().save(*args, **kwargs)
        
        
    
    def __str__(self):
        return f"{self.package_name}"
    
    
class Hero(models.Model):
    hero_text = models.CharField(max_length=150)
    hero_description = models.TextField()

    def __str__(self):
        return self.hero_text
    

class About(models.Model):
    img = models.ImageField(upload_to="about_img/")
    description = models.TextField()
    
    def __str__(self):
        return self.description[:20]

    def image_tag(self):
        return mark_safe('<img src="%s" width="80" />' % (self.img.url))
    
class Project(models.Model):
    img = models.ImageField(upload_to="projects/")
    alt = models.CharField(default="project_img")

    def __str__(self):
        return self.alt
    
    def imga_tag(self):
        return mark_safe('<img src="%s" width="80" />' % (self.img.url))

    

organizer/views.py
from django.shortcuts import render,redirect
from django.contrib import messages 
from django.contrib.auth.decorators import login_required
from . import models
import re
from decimal import Decimal

# Logics
def separate_comma(to_array):
    return [item.strip() for item in re.split(r'[, \n]+', to_array) if item.strip()]

def separate_newline(to_array):
    return [item.strip() for item in to_array.split("\n")]
    
    
# Create your views here.
def index(request):
    return render(request, 'organizer/index.html')

def packages(request):
    package = models.Package.objects.all().order_by('-id')
    if request.method == "POST":
        package_name = request.POST.get('package_name')
        package_price = request.POST.get('package_price')
        package_inclusion = separate_comma(request.POST.get('package_inclusion'))
        
        package = models.Package(package_name=package_name, package_price=package_price, package_inclusion=package_inclusion)
        package.save()
        messages.success(request, "Package addedd successfully!")
        
        return redirect('organizer:packages')
    else:
        return render(request, 'organizer/packages.html', {'packages': package})
    
def update_package(request, id):
    if request.method == 'POST':
        package = models.Package.objects.get(id=id)
        package.package_name = request.POST['update_package_name']
        package.package_price = Decimal(request.POST['update_package_price'])
        package.package_downpayment = package.package_price * Decimal('0.2')
        package.package_inclusion = separate_comma(request.POST['update_package_inclusion'])
        package.save()
        messages.success(request, "Package updated successfully!")
        
    else:
        pass
    return redirect('organizer:packages')

def delete_package(request, id):
    package = models.Package.objects.get(id=id)
    package.delete()
    messages.success(request, "Package deleted successfully!")
    return redirect('organizer:packages')

def bookings(requst):
    return render(requst, 'organizer/bookings.html')

def confrim_payments(request):
    return render(request, 'organizer/pending-payments.html')

def payment_history(request):
    return render(request, 'organizer/payment-history.html')

def manage_clients(request):
    return render(request, 'organizer/clients.html')

def manage_suppliers(request):
    return render(request, 'organizer/suppliers.html')

def system_settings(request):
    hero = models.Hero.objects.first()
    about = models.About.objects.first()
    projects = models.Project.objects.order_by('-id')
    return render(request, 'organizer/system_settings.html', {'hero':hero, 'about':about, 'projects':projects})

def update_hero(request):
    hero = models.Hero.objects.first()
    
    if request.method == "POST":
        hero_text = request.POST.get('hero_text')
        hero_description = request.POST.get('hero_description')
        
        if hero_text == hero.hero_text and hero_description == hero.hero_description:
            messages.info(request, "No changes detected")
        else:
            messages.success(request, "Successfully updated hero section.")
            hero.hero_text = hero_text
            hero.hero_description = hero_description
            hero.save()
        
    return redirect('organizer:system-settings')

def update_about(request):
    about = models.About.objects.first()
    
    if request.method == "POST":
        description = request.POST.get('about_description')
        img = request.FILES.get('image_input')
        print(img)
        if description == about.description and (img is None or img == about.img):
            messages.info(request, "No changes detected")
        else:
            messages.success(request, "Successfully updated about section.")
            if img:
                about.img = img
            about.description = description
            about.save()
    return redirect('organizer:system-settings')

def activity_logs(request):
    return render(request, 'organizer/activity-logs.html')

organizer/templates/organizer/activity-logs.html
{% extends 'components/base.html' %}
{% load static %}
{% block title %}
  E-Events | Activity Logs
{% endblock %}

{% block content %}
  {% include 'components/sidebar.html' %}

  <section class="section activity-logs mt-5">
    <div class="card mb-4">
      <div class="card-header mb-4 t-header">
        <i class="bi bi-table"></i>
      </div>
      <div class="card-body table-responsive">
        <table class="table table-hover datatable">
          <thead>
            <tr>
              <th>ID</th>
              <th>User</th>
              <th>Date</th>
              <th>Time</th>
              <th>Action</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>Julius Orit</td>
              <td>2/18/2025</td>
              <td>10:00 AM</td>
              <td>
                <p class="bg-success d-inline-block px-2 text-light action">Added</p>
              </td>
              <td>Created a new package</td>
            </tr>
            <tr>
              <td>2</td>
              <td>Julius Orit</td>
              <td>2/14/2025</td>
              <td>12:00 AM</td>
              <td>
                <p class="bg-warning d-inline-block px-2 text-dark action">Updated</p>
              </td>
              <td>Update package #1</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </section>

  
{% endblock %}

organizer/templates/organizer/bookings.html
{% extends "components/base.html" %}
{% load static %}
{% block title %}E-Events | Bookings{% endblock title %}

{% block content %}
{% include "components/sidebar.html" %}


{% endblock content %}

organizer/templates/organizer/clients.html
{% extends "components/base.html" %}
{% load static %}
{% block title %}E-Events | Clients{% endblock title %}

{% block content %}
{% include "components/sidebar.html" %}



{% endblock content %}

organizer/templates/organizer/packages.html
{% extends 'components/base.html' %}
{% load static %}
{% block title %}
  E-Events | Packages
{% endblock %}

{% block content %}
  {% include 'components/sidebar.html' %}

   <section class="section packages mt-5 px-3">
    <div class="card mb-4">
      <div class="card-header mb-4 t-header d-flex align-items-center justify-content-between">
        <i class="bi bi-table"></i>
        {% comment %} <a class="btn btn-success" data-bs-toggle="modal" data-bs-target="#add_package">
          <i class="bi bi-plus"></i>
          <span>Add Package</span>
        </a> {% endcomment %}
      </div>
      <div class="card-body table-responsive">
        <table class="table table-hover text-center">
          <thead>
            <tr>
              <th>No.</th>
              <th>Package Name</th>
              <th>Price</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {% for package in packages %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ package.package_name }}</td>
                <td>{{ package.package_price }}</td>
                <td class="d-flex justify-content-center gap-2">
                  <button class="btn btn-info view" data-bs-toggle="modal" data-bs-target="#view_package_modal_{{ package.id }}"><i class="bi bi-eye"></i></button>
                  <button class="btn btn-warning view" data-bs-toggle="modal" data-bs-target="#update_package_modal_{{ package.id }}"><i class="bi bi-pen"></i></button>
                  {% comment %} <button class="btn btn-danger view" data-bs-toggle="modal" data-bs-target="#delete_package_modal_{{ package.id }}"><i class="bi bi-trash3"></i></button> {% endcomment %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section> 

  {% comment %}Add Modal{% endcomment %}
  <div class="modal fade package_modal" id="add_package">
    <div class="modal-dialog modal-lg modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header bg-light text-dark">
          <h3 class="modal-title">Add New Package</h3>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <div class="modal-body">
          <form action="{% url 'organizer:packages' %}" id="data_form" method="post">
            {% csrf_token %}
            <div class="text_field">
              <div class="">
                <label for="package_name">Package Name</label>
                <input type="text" name="package_name" id="package_name" required />
              </div>
              <div class="">
                <label for="package_name">Price</label>
                <input type="number" name="package_price" id="package_price" maxlength="6" required />
              </div>
              <div class="">
                <label for="package_name">Services</label>
                <textarea name="package_inclusion" id="package_inclusion" rows="5"></textarea>
              </div>
            </div>
          </form>
        </div>

        <div class="modal-footer text-center">
          <button type="submit" form="data_form" class="add_package_btn">Add Package <i class="bi bi-box-arrow-in-right"></i></button>
        </div>
      </div>
    </div>
  </div>
  {% comment %}End of add modal{% endcomment %}

  {% for package in packages %}
    {% comment %}View Modal{% endcomment %}
    <div class="modal fade package_modal" id="view_package_modal_{{ package.id }}">
      <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header bg-light text-dark">
            <h3 class="modal-title">Package Detail</h3>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>

          <div class="modal-body">
            <form action="{% url 'organizer:packages' %}" id="data_form{{ package.id }}" method="post">
              {% csrf_token %}
              <input type="hidden" name="package_id" id="{{ package.id }}" />
              <div class="text_field">
                <div class="">
                  <label for="package_name">Package Name</label>
                  <input type="text" name="package_name" id="package_name{{ package.id }}" value="{{ package.package_name }}" readonly />
                </div>
                <div class="">
                  <label for="package_name">Price</label>
                  <input type="number" name="package_price" id="package_price{{ package.package_id }}" value="{{ package.package_price }}" maxlength="6" readonly />
                </div>
                <div class="">
                  <label for="package_name">Pacakage Inclusions</label>
                  <textarea name="package_inclusion" id="package_inclusion{{ package.package_id }}" rows="5" readonly>{{ package.package_inclusion|join:'&#10;' }}</textarea>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    {% comment %}End of view modal{% endcomment %}

    {% comment %}Update modal{% endcomment %}
    <div class="modal fade package_modal" id="update_package_modal_{{ package.id }}">
      <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header bg-light text-dark">
            <h3 class="modal-title">Update Package</h3>
            <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>

          <div class="modal-body">
            <form action="{% url 'organizer:update-package' package.id %}" id="update_form{{ package.id }}" method="post">
              {% csrf_token %}
              <input type="hidden" name="package_id" id="{{ package.id }}" />
              <div class="text_field">
                <div class="">
                  <label for="package_name">Package Name</label>
                  <input type="text" name="update_package_name" id="package_name{{ package.id }}" value="{{ package.package_name }}" required />
                </div>
                <div class="">
                  <label for="package_name">Price</label>
                  <input type="number" name="update_package_price" id="package_price{{ package.package_id }}" value="{{ package.package_price }}" maxlength="6" required />
                </div>
                <div class="">
                  <label for="package_name">Pacakage Inclusions</label>
                  <textarea name="update_package_inclusion" id="package_inclusion{{ package.package_id }}" rows="5" required>{{ package.package_inclusion|join:', ' }}</textarea>
                </div>
              </div>
            </form>
          </div>
          <div class="modal-footer text-center">
            <button type="submit" form="update_form{{ package.id }}" class="add_package_btn">Update Package <i class="bi bi-box-arrow-in-right"></i></button>
          </div>
        </div>
      </div>
    </div>
    {% comment %}End of update modal{% endcomment %}

    {% comment %}Delete Modal{% endcomment %}
    <div class="modal fade package_modal" id="delete_package_modal_{{ package.id }}">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header bg-light text-dark">
            <h3 class="modal-title">Delete Package</h3>
            <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p>
              Are you sure to delete <strong>{{ package.package_name }}</strong>?
            </p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <a href="{% url 'organizer:delete-package' package.id %}" class="btn btn-danger">Delete</a>
          </div>
        </div>
      </div>
    </div>
    {% comment %}End of delete modal{% endcomment %}
  {% endfor %}

  {% if messages %}
    <script>
      
      function confirmDelete(deleteUrl) {
        Swal.fire({
          title: "Are you sure?",
          text: "This action cannot be undone!",
          icon: "warning",
          showCancelButton: true,
          confirmButtonColor: "#d33",
          cancelButtonColor: "#3085d6",
          confirmButtonText: "Yes, delete it!"
        }).then((result => {
          if (result.isConfirmed) {
            window.location.href = deleteUrl;
          }
        }));
      }
      
      document.addEventListener("DOMContentLoaded", function() {
        {% for message in messages %}
            Swal.fire({
                icon: "success",
                title: "Success!",
                text: "{{ message }}",
                showConfirmButton: false,
                timer: 2000
            });
        {% endfor %}
      });
    </script>
  {% endif %}

  
{% endblock %}

organizer/templates/organizer/payment-history.html
{% extends "components/base.html" %}
{% load static %}
{% block title %}E-Events | Payment History{% endblock title %}

{% block content %}
{% include "components/sidebar.html" %}



{% endblock content %}

organizer/templates/organizer/pending-payments.html
{% extends "components/base.html" %}
{% load static %}
{% block title %}E-Events | Confirm Payments{% endblock title %}

{% block content %}
{% include "components/sidebar.html" %}



{% endblock content %}

organizer/templates/organizer/suppliers.html
{% extends "components/base.html" %}
{% load static %}
{% block title %}E-Events | Suppliers{% endblock title %}

{% block content %}
{% include "components/sidebar.html" %}




{% endblock content %}

organizer/templates/organizer/system_settings.html
{% extends 'components/base.html' %}

{% block title %}
  E-Events | Settings
{% endblock %}

{% block content %}
  {% include 'components/sidebar.html' %}

  <section class="section system_settings mt-3">
    <div class="card">
      <div class="card-header py-2 px-3">
        <ul class="nav nav-pills" id="pills-tab" role="tablist">
          <li class="nav-item" role="presentation">
            <button class="nav-link active" id="pills-hero-tab" data-bs-toggle="pill" data-bs-target="#pills-hero" type="button" role="tab" aria-controls="pills-hero" aria-selected="true">Hero</button>
          </li>
          <li class="nav-item" role="presentation">
            <button class="nav-link" id="pills-about_us-tab" data-bs-toggle="pill" data-bs-target="#pills-about_us" type="button" role="tab" aria-controls="pills-about_us" aria-selected="false">About us</button>
          </li>
          <li class="nav-item" role="presentation">
            <button class="nav-link" id="pills-projects-tab" data-bs-toggle="pill" data-bs-target="#pills-projects" type="button" role="tab" aria-controls="pills-about_us" aria-selected="false">Projects</button>
          </li>
          <li class="nav-item" role="presentation">
            <button class="nav-link" id="pills-awards-tab" data-bs-toggle="pill" data-bs-target="#pills-awards" type="button" role="tab" aria-controls="pills-about_us" aria-selected="false">Awards</button>
          </li>
          <li class="nav-item" role="presentation">
            <button class="nav-link" id="pills-faq-tab" data-bs-toggle="pill" data-bs-target="#pills-faq" type="button" role="tab" aria-controls="pills-about_us" aria-selected="false">FAQ's</button>
          </li>
          <li class="nav-item" role="presentation">
            <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-about_us" aria-selected="false">Profile</button>
          </li>
        </ul>
      </div>
      <div class="card-body">
        <div class="tab-content" id="pills-tab_content">
          <div class="tab-pane fade show active" id="pills-hero" role="tabpanel" aria-labelledby="pills-hero" tabindex="0">
            <form action="{% url 'organizer:update-hero' %}" enctype="multipart/form-data" method="post">
              {% csrf_token %}
              <br>
              <div class="mb-3">
                <label for="hero_text" class="form-label">Hero:</label>
                <input type="text" class="form-control" required value="{{hero.hero_text}}" name="hero_text" id="hero_text" autocomplete="off"> 
              </div>
              <div class="mb-3">
                <label for="hero_text" class="form-label">Description:</label>
                <textarea name="hero_description" id="hero_description" class="form-control" rows="5" required>{{hero.hero_description}}</textarea>
              </div>
              <button type="submit" class="save_btn">Save</button>
            </form>
          </div>

          <div class="tab-pane fade" id="pills-about_us" role="tabpanel" aria-labelledby="pills-about_us" tabindex="0">
            <form action="{% url 'organizer:update-about' %}" enctype="multipart/form-data" method="post">
              {% csrf_token %}
              <br>
              <div class="mb-3">
                <label for="about_img" class="form-label d-block">About Image:</label>
                <img src="{{about.img.url}}" alt="" class="img-fluid" width="200" id="preview_image">
                <input type="file" class="form-control mt-2" accept="image/*" id="image_input" name="image_input">
                
              </div>
              <div class="mb-3">
                <label for="about_description" class="form-label">Description:</label>
                <textarea name="about_description" id="about_description" class="form-control" rows="5" required>{{about.description}}</textarea>
              </div>
              <button type="submit" class="save_btn">Save</button>
            </form>
          </div>

          <div class="tab-pane fade" id="pills-projects" role="tabpanel" aria-labelledby="pills-projects" tabindex="0">
            <br>
            <div class="text-end mb-2">
              <button class="btn btn-primary vertical-middle">Add Project <i class="bi bi-plus"></i></button>
            </div>
            <div class="row gy-2">
              {% for project in projects %}
              <div class="col-lg-4 col-md-6">
                <div class="card">
                  <div class="card-img">
                    <img src="{{project.img.url}}" alt="" class="img-fluid" data-aos="fade-up" data-aos-delay="100" />
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>

        </div>

      </div>
    </div>
  </section>
{% endblock %}