chat/urls.py
from django.urls import path
from . import views

app_name = "chat"


urlpatterns = [
    # path('', views.chat, name="chat"),
   path('c/<str:room_name>/', views.chat_box, name='chat-user'),
]

expo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('organizer/', include('organizer.urls', namespace="organizer")),
    path('', include('user.urls', namespace="user")),
    path('message/', include('chat.urls', namespace="message")),
    path('admin/', admin.site.urls),
    path('', include('paypal.standard.ipn.urls'))
]

organizer/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = "organizer"

urlpatterns = [
    path('dashboard/', views.index, name="dashboard"),
    path('packages/', views.packages, name="packages"),
    path('update-package/<int:id>/', views.update_package, name="update-package"),
    path('delete-package/<int:id>/', views.delete_package, name="delete-package"),
    path('bookings/', views.bookings, name="bookings"),
    path('confirm-payments/', views.confrim_payments, name="confirm-payments"),
    path('payment-history/', views.payment_history, name="payment-history"),
    path('clients/', views.manage_clients, name="clients"),
    path('suppliers/', views.manage_suppliers, name="suppliers"),
    
    path('system-settings/', views.system_settings, name="system-settings"),
    path('system-settings/update-hero', views.update_hero, name="update-hero"),
    path('system-settings/update-about', views.update_about, name="update-about"),
    
    
    path('activity-logs/', views.activity_logs, name="activity-logs"),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "user"

urlpatterns = [
    path('', views.landing_page, name="landingpage"),
    path('login/', views.log_in, name="login"),
    path('logout/', views.log_out, name="logout"),
    path('register/', views.register, name="register"),
    path('activate/<uidb64>/<token>', views.activate, name="activate"),
    path('forgot_password', views.forgot_password, name="forgotpassword"),
    path('confirm_otp', views.confirm_otp, name="confirmotp"),
    path('new_password/', views.new_password, name="newpassword"),
    path('user/dashboard/', views.dashboard, name="dashboard"),

    path('user/booking/', views.booking, name="booking"),
    path('user/booking/create-booking/', views.create_booking, name="create-booking"),
    path('user/booking/create-booking/proceed-to-payment', views.proceed_to_payment, name="proceed-to-payment"),
    path('user/booking-confirmation/', views.booking_confirmed, name='booking-confirmation'),
    
    path('user/payment-history', views.payment_history, name="payment-history"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organizer/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.utils.html import mark_safe
from decimal import Decimal
# Create your models here.

class Package(models.Model):
    PACKAGE_TYPES = [
        ('fixed', 'Fixed'),
        ('custom', 'Custom'),
    ]

    package_name = models.CharField(max_length=150, unique=True)
    package_type = models.CharField(max_length=10, choices=PACKAGE_TYPES, default='Fixed')
    package_price = models.DecimalField(max_digits=8, decimal_places=2)
    package_downpayment = models.DecimalField(max_digits=8, decimal_places=2)
    package_inclusion = ArrayField(models.CharField(max_length=150), null=True)
    
    def save(self, *args, **kwargs):
        if self.package_type == "Fixed":
            self.package_downpayment =  Decimal(self.package_price) * Decimal('0.2')
        
        super().save(*args, **kwargs)
        
        
    
    def __str__(self):
        return f"{self.package_name}"
    
    
class Hero(models.Model):
    hero_text = models.CharField(max_length=150)
    hero_description = models.TextField()

    def __str__(self):
        return self.hero_text
    

class About(models.Model):
    img = models.ImageField(upload_to="about_img/")
    description = models.TextField()
    
    def __str__(self):
        return self.description[:20]

    def image_tag(self):
        return mark_safe('<img src="%s" width="80" />' % (self.img.url))
    
class Project(models.Model):
    img = models.ImageField(upload_to="projects/")
    alt = models.CharField(default="project_img")

    def __str__(self):
        return self.alt
    
    def imga_tag(self):
        return mark_safe('<img src="%s" width="80" />' % (self.img.url))

    

organizer/views.py
from django.shortcuts import render,redirect
from django.contrib import messages 
from django.contrib.auth.decorators import login_required
from . import models
import re
from decimal import Decimal

# Logics
def separate_comma(to_array):
    return [item.strip() for item in re.split(r'[, \n]+', to_array) if item.strip()]

def separate_newline(to_array):
    return [item.strip() for item in to_array.split("\n")]
    
    
# Create your views here.
def index(request):
    return render(request, 'organizer/index.html')

def packages(request):
    package = models.Package.objects.all().order_by('-id')
    if request.method == "POST":
        package_name = request.POST.get('package_name')
        package_price = request.POST.get('package_price')
        package_inclusion = separate_comma(request.POST.get('package_inclusion'))
        
        package = models.Package(package_name=package_name, package_price=package_price, package_inclusion=package_inclusion)
        package.save()
        messages.success(request, "Package addedd successfully!")
        
        return redirect('organizer:packages')
    else:
        return render(request, 'organizer/packages.html', {'packages': package})
    
def update_package(request, id):
    if request.method == 'POST':
        package = models.Package.objects.get(id=id)
        package.package_name = request.POST['update_package_name']
        package.package_price = Decimal(request.POST['update_package_price'])
        package.package_downpayment = package.package_price * Decimal('0.2')
        package.package_inclusion = separate_comma(request.POST['update_package_inclusion'])
        package.save()
        messages.success(request, "Package updated successfully!")
        
    else:
        pass
    return redirect('organizer:packages')

def delete_package(request, id):
    package = models.Package.objects.get(id=id)
    package.delete()
    messages.success(request, "Package deleted successfully!")
    return redirect('organizer:packages')

def bookings(requst):
    return render(requst, 'organizer/bookings.html')

def confrim_payments(request):
    return render(request, 'organizer/pending-payments.html')

def payment_history(request):
    return render(request, 'organizer/payment-history.html')

def manage_clients(request):
    return render(request, 'organizer/clients.html')

def manage_suppliers(request):
    return render(request, 'organizer/suppliers.html')

def system_settings(request):
    hero = models.Hero.objects.first()
    about = models.About.objects.first()
    projects = models.Project.objects.order_by('-id')
    return render(request, 'organizer/system_settings.html', {'hero':hero, 'about':about, 'projects':projects})

def update_hero(request):
    hero = models.Hero.objects.first()
    
    if request.method == "POST":
        hero_text = request.POST.get('hero_text')
        hero_description = request.POST.get('hero_description')
        
        if hero_text == hero.hero_text and hero_description == hero.hero_description:
            messages.info(request, "No changes detected")
        else:
            messages.success(request, "Successfully updated hero section.")
            hero.hero_text = hero_text
            hero.hero_description = hero_description
            hero.save()
        
    return redirect('organizer:system-settings')

def update_about(request):
    about = models.About.objects.first()
    
    if request.method == "POST":
        description = request.POST.get('about_description')
        img = request.FILES.get('image_input')
        print(img)
        if description == about.description and (img is None or img == about.img):
            messages.info(request, "No changes detected")
        else:
            messages.success(request, "Successfully updated about section.")
            if img:
                about.img = img
            about.description = description
            about.save()
    return redirect('organizer:system-settings')

def activity_logs(request):
    return render(request, 'organizer/activity-logs.html')

organizer/templates/components/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}

      {% endblock %}
    </title>
    <!-- Google Organizer Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet" />

    <!-- Vendor Organizer CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/vendor/quill/quill.snow.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet" />

    <!-- Template Organizer CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />

    {% block css %}

    {% endblock %}
  </head>
  <body class="d-flex flex-column h-100">
    <main id="main" class="main">
      <div class="pagetitle">
        {% if breadcrumbs %}
          {% with last_crumb=breadcrumbs|last %}
            <h1>{{ last_crumb.name|capfirst }}</h1> 
          {% endwith %}

          <nav>
            <ol class="breadcrumb">
              {% for crumb in breadcrumbs %}
                {% if forloop.last %}
                  <li class="breadcrumb-item active">{{ crumb.name }}</li>
                {% else %}
                  <li class="breadcrumb-item">
                    {{ crumb.name }}
                  </li>
                {% endif %}
              {% endfor %}
            </ol>
          </nav>
        {% endif %}
      </div>

      {% block content %}

      {% endblock %}
    </main>
    {% include 'components/footer.html' %}
    {% if messages %}
      <script>
      document.addEventListener("DOMContentLoaded", function() {
        {% for message in messages %}
            Swal.fire({
              icon: "{% if message.tags == 'success' %}success{% elif message.tags == 'error' %}error{% elif message.tags == 'warning' %}warning{% else %}info{% endif %}",
              title: "{% if message.tags == 'success' %}Success!{% elif message.tags == 'error' %}Error!{% else %}Notice{% endif %}",
                text: "{{ message|safe }}",
            });
        {% endfor %}
      });
    </script>
    {% endif %}
    {% block js %}

    {% endblock %}

    {% comment %}Sweet Alert{% endcomment %}
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/chart.js/chart.umd.js' %}"></script>
    <script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
    <script src="{% static 'assets/vendor/quill/quill.js' %}"></script>
    <script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
    <script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>
  </body>
</html>

organizer/templates/components/footer.html
<footer id="footer" class="footer mt-auto">
    <div class="copyright">
      &copy; Copyright <strong><span>Vin Russel Jarcia</span></strong>. <br />
      &copy; Copyright <strong><span>Expo 2025</span></strong>. <br />All Rights Reserved
    </div>
  </footer>

organizer/templates/components/sidebar.html
{% load static %}
<header id="header" class="header fixed-top d-flex align-items-center">
  <div class="d-flex align-items-center justify-content-between">
    <a href="{% url 'organizer:dashboard' %}" class="logo d-flex align-items-center">
      <img src="" alt="" />
      <span class="d-none d-lg-block">E-Events</span>
    </a>
    <i class="bi bi-list toggle-sidebar-btn"></i>
  </div>
  <!-- End Logo -->

  <nav class="header-nav ms-auto">
    <ul class="d-flex align-items-center">
      {% comment %}
      <li class="nav-item d-block d-lg-none">
        <a class="nav-link nav-icon search-bar-toggle" href="#"><i class="bi bi-search"></i></a>
      </li>
      <!-- End Search Icon -->
      {% endcomment %}

      <li class="nav-item dropdown">
        <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
          <i class="bi bi-bell"></i>
          <span class="badge bg-primary badge-number">4</span>
        </a><!-- End Notification Icon -->

        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
          <li class="dropdown-header">
            You have 4 new notifications
            {% comment %} <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a> {% endcomment %}
          </li>
          <li>
            <hr class="dropdown-divider" />
          </li>

          <li class="notification-item">
            <i class="bi bi-exclamation-circle text-warning"></i>
            <div>
              <h4>Lorem Ipsum</h4>
              <p>Quae dolorem earum veritatis oditseno</p>
              <p>30 min. ago</p>
            </div>
          </li>

          <li>
            <hr class="dropdown-divider" />
          </li>

          <li class="notification-item">
            <i class="bi bi-x-circle text-danger"></i>
            <div>
              <h4>Atque rerum nesciunt</h4>
              <p>Quae dolorem earum veritatis oditseno</p>
              <p>1 hr. ago</p>
            </div>
          </li>

          <li>
            <hr class="dropdown-divider" />
          </li>

          <li class="notification-item">
            <i class="bi bi-check-circle text-success"></i>
            <div>
              <h4>Sit rerum fuga</h4>
              <p>Quae dolorem earum veritatis oditseno</p>
              <p>2 hrs. ago</p>
            </div>
          </li>

          <li>
            <hr class="dropdown-divider" />
          </li>

          <li class="notification-item">
            <i class="bi bi-info-circle text-primary"></i>
            <div>
              <h4>Dicta reprehenderit</h4>
              <p>Quae dolorem earum veritatis oditseno</p>
              <p>4 hrs. ago</p>
            </div>
          </li>

          <li>
            <hr class="dropdown-divider" />
          </li>
          <li class="dropdown-footer">
            <a href="#">Show all notifications</a>
          </li>
        </ul>
        <!-- End Notification Dropdown Items -->
      </li>
      <!-- End Notification Nav -->

      <li class="nav-item dropdown">
        <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
          <i class="bi bi-chat-left-text"></i>
          <span class="badge bg-success badge-number">3</span>
        </a><!-- End Messages Icon -->

        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow messages">
          <li class="dropdown-header">
            You have 3 new messages
            <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
          </li>
          <li>
            <hr class="dropdown-divider" />
          </li>

          <li class="message-item">
            <a href="#">
              <img src="assets/img/messages-1.jpg" alt="" class="rounded-circle" />
              <div>
                <h4>Maria Hudson</h4>
                <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                <p>4 hrs. ago</p>
              </div>
            </a>
          </li>
          <li>
            <hr class="dropdown-divider" />
          </li>

          <li class="message-item">
            <a href="#">
              <img src="assets/img/messages-2.jpg" alt="" class="rounded-circle" />
              <div>
                <h4>Anna Nelson</h4>
                <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                <p>6 hrs. ago</p>
              </div>
            </a>
          </li>
          <li>
            <hr class="dropdown-divider" />
          </li>

          <li class="message-item">
            <a href="#">
              <img src="assets/img/messages-3.jpg" alt="" class="rounded-circle" />
              <div>
                <h4>David Muldon</h4>
                <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                <p>8 hrs. ago</p>
              </div>
            </a>
          </li>
          <li>
            <hr class="dropdown-divider" />
          </li>

          <li class="dropdown-footer">
            <a href="#">Show all messages</a>
          </li>
        </ul>
        <!-- End Messages Dropdown Items -->
      </li>
      <!-- End Messages Nav -->

      <li class="nav-item dropdown pe-3">
        <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
          <img src="{% static 'assets/img/avatar.svg' %}" alt="Profile" class="rounded-circle" />
          <span class="d-none d-md-block dropdown-toggle ps-2">{{user.first_name|slice:":1"}}.  {{user.last_name}}</span>
        </a><!-- End Profile Iamge Icon -->

        {% if user.is_authenticated %}
        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
          <li class="dropdown-header">
            <h6>{{user.first_name}} {{ user.last_name}}</h6>
            <span>Organizer</span>
          </li>
          <li>
            <hr class="dropdown-divider" />
          </li>

          <li>
            <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
              <i class="bi bi-person"></i>
              <span>My Profile</span>
            </a>
          </li>
          <li>
            <hr class="dropdown-divider" />
          </li>

          <li>
            <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
              <i class="bi bi-gear"></i>
              <span>Account Settings</span>
            </a>
          </li>
          <li>
            <hr class="dropdown-divider" />
          </li>

          {% comment %} <li>
            <a class="dropdown-item d-flex align-items-center" href="pages-faq.html">
              <i class="bi bi-question-circle"></i>
              <span>Need Help?</span>
            </a>
          </li>
          <li>
            <hr class="dropdown-divider" />
          </li> {% endcomment %}

          <li>
            <a class="dropdown-item d-flex align-items-center" href="{% url 'user:logout' %}">
              <i class="bi bi-box-arrow-right"></i>
              <span>Sign Out</span>
            </a>
          </li>
        </ul>
        <!-- End Profile Dropdown Items -->
      </li>
      <!-- End Profile Nav -->
    </ul>
    {% endif %}
  </nav>
  <!-- End Icons Navigation -->
</header>
<!-- ======= Sidebar ======= -->
<aside id="sidebar" class="sidebar">
  <ul class="sidebar-nav" id="sidebar-nav">
    <li class="nav-item">
      <a class="nav-link collapsed" href="{% url 'organizer:dashboard' %}">
        <i class="bi bi-grid"></i>
        <span>Dashboard</span>
      </a>
    </li>
    <!-- End Dashboard Nav -->

    <li class="nav-item">
      <a href="{% url 'organizer:packages' %}" class="nav-link collapsed">
        <i class="bi bi-box"></i>
        <span>Packages</span>
      </a>
    </li>

    <li class="nav-item">
      <a href="{% url 'organizer:bookings' %}" class="nav-link collapsed">
        <i class="bi bi-book"></i>
        <span>Bookings</span>
      </a>
    </li>

    <li class="nav-item">
      <a href="" class="nav-link collapsed" data-bs-target="#payments-nav" data-bs-toggle="collapse">
        <i class="bi bi-credit-card"></i>
        <span>Payments</span>
        <i class="bi bi-chevron-down ms-auto"></i>
      </a>
      <ul id="payments-nav" class="nav-content collapse" data-bs-parent="#sidebar-nav">
        <li>
          <a href="{% url 'organizer:confirm-payments' %}"><i class="bi bi-circle"></i><span>Confirm Payments</span></a>
        </li>
        <li>
          <a href="{% url 'organizer:payment-history' %}"><i class="bi bi-circle"></i><span>Payment History</span></a>
        </li>
      </ul>
    </li>

    <li class="nav-item">
      <a href="{% url 'organizer:clients' %}" class="nav-link collapsed" >
        <i class="bi bi-person"></i>
        <span>Users</span>
      </a>
    </li>

    <li class="nav-item">
      <a href="{% url 'organizer:system-settings' %}" class="nav-link collapsed">
        <i class="bi bi-gear"></i>
        <span>System Settings</span>
      </a>
    </li>

    <li class="nav-item">
      <a href="{% url 'organizer:activity-logs' %}" class="nav-link collapsed">
        <i class="bi bi-clock-history"></i>
        <span>Activity Logs</span>
      </a>
    </li>
  </ul>
  
</aside>